### ISSUE TITLE
validate get error

### ISSUE THREAD

**Issue by watsy0007** [mirego/activerecord_json_validator#20]
i got error
```
(0.3ms)  BEGIN
   (0.2ms)  ROLLBACK
Errno::ENOENT: No such file or directory @ rb_sysopen - {"type"=>"object", "$schema"=>"http://json-schema.org/draft-04/schema#", "properties"=>{"cases"=>{"type"=>"object"}, "work_experiences"=>{"type"=>"object"}, "educations"=>{"type"=>"object"}, "links"=>{"type"=>"object"}}}
	from /Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
	from /Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	from /Users/watsy/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/schema/reader.rb:98:in `read_uri'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/schema/reader.rb:68:in `read'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:527:in `rescue in initialize_schema'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:515:in `initialize_schema'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:50:in `block in initialize'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:50:in `synchronize'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:50:in `initialize'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:278:in `new'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/json-schema-2.5.1/lib/json-schema/validator.rb:278:in `fully_validate'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/activerecord_json_validator-1.0.0/lib/active_record/json_validator/validator.rb:16:in `validate_each'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/activemodel-4.2.3/lib/active_model/validator.rb:151:in `block in validate'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/activemodel-4.2.3/lib/active_model/validator.rb:148:in `each'
	from /Users/watsy/.rvm/gems/ruby-2.2.0/gems/activemodel-4.2.3/lib/active_model/validator.rb:148:in `validate'
```

**Comment by ojab** [comment]
In case of String schema it should be path to schema file, not schema itself. So most likely you should remove File.read from schema initialization.

**Comment by remiprev** [comment]
@watsy0007 Can you specify how you are using the validator? Something like:

```ruby
class User < ActiveRecord::Base
  PROFILE_JSON_SCHEMA = {
    "type" => "object",
    "$schema" => "http:\/\/json-schema.org\/draft-04\/schema#",
    "properties" => {
      "cases" => {
        "type" => "object"
      },
      "work_experiences" => {
        "type" => "object"
      },
      "educations" => {
        "type" => "object"
      },
      "links" => {
        "type" => "object"
      }
    }
  }

  validates :profile, presence: true, json: { schema: PROFILE_JSON_SCHEMA }
end
```

Thank you!

**Comment by remiprev** [comment]
I’m going to close this issue since there hasn’t been any activity for several months.
